### ISSUE TITLE
Embed is content is not parsed

### ISSUE THREAD

**Issue by xplosionmind** [photogabble/eleventy-plugin-interlinker#10]
Unfortunately, the plugin is not working for pages embedding.

Please, refer to the branch `interlinker` of [xplosionmind/tommi.space](https://github.com/xplosionmind/tommi.space/tree/interlinker).

In `content/jam/public/Woody Allen.md` there is an embed link to `content/jam/public/A Rainy Day in New York`.

In the code I can see that `<div class='wikilink-embed'></div>` is loaded, but no content is inside it.

What could be the cause?

Thanks a lot!

**Comment by carbontwelve** [comment]
Hello @xplosionmind, thankyou for giving my plugin a go. I can confirm that you're experiencing a bug in my implementation of the embed.

I don't currently set the `content` variable when rendering the embed template. In my repository I make use of `{% block content %}{% endblock %}`, I'm working on the plugin this weekend and the next release will include a bugfix for your issue.

**Comment by carbontwelve** [comment]
@xplosionmind you should find this issue fixed in [v1.0.4](https://github.com/photogabble/eleventy-plugin-interlinker/releases/tag/v1.0.4) please reopen this issue if you find that to not be the case.
